# For trusted publishing releases, it is required to start all releases from a single workflow file.
name: publish

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Dist tag for the release. If you chose something different than "canary", make sure to delete it once it is not needed anymore.'
        type: string
        required: false
        default: 'canary'

permissions: {}

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - uses: sap/cloud-sdk-js/.github/actions/setup@main
        with:
          pnpm-version: ''
          node-version: 24 # Will install npm 11 needed for trusted publishing
          package-manager-cache: false
          registry-url: 'https://registry.npmjs.org'
          token: ${{ github.token }}
          persist-credentials: false

      - name: Fetch full git history
        run: git fetch --filter=blob:none --tags --unshallow || git fetch --filter=blob:none --tags

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@c47fa68bd43bb8ae0bae7e558622593deebf5955 # v2.0.0-next.3
        with:
          publish-script: pnpm changeset publish
          version-script: pnpm version-packages
          commit-message: 'chore: version packages'
          pr-title: 'chore: version packages'
          github-token: ${{ github.token }}

  delegate_to_canary_job:
    if: ${{ github.event_name != 'push' }}
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/publish-canary.yml
    with:
      tag: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || 'canary' }}
